const NewestCourse = [
    {
        id: "1",
        courseTag: "Art & Design",
        lesson: "21 Lesson",
        courseRating: "4.5 (42)",
        coursePrice: "62.00",
        courseOldPrice: "97.00",
        courseImage: "./images/course-1.jpg",
        courseName: "Become a product Manager learn the skills & job.",
        courseOwner: "Jassica Miller",
        bgClassName: "bg-color-1",    
        textClassName: "text-color-1",
        moreDetails: "More Details",  
    },
    {
        id: "2",
        courseTag: "Mechanical",
        lesson: "22 Lesson",
        courseRating: "4.6 (46)",
        coursePrice: "62.00",
        courseOldPrice: "95.00",
        courseImage: "./images/course-2.jpg",
        courseName: "Fundamentals of music theory Learn new",
        courseOwner: "Jassica Miller 2",
        bgClassName: "bg-color-2",
        textClassName: "text-color-2",
        moreDetails: "More Details",  
    },
    {
        id: "3",
        courseTag: "Development",
        lesson: "25 Lesson",
        courseRating: "4.7 (52)",
        coursePrice: "69.00",
        courseOldPrice: "99.00",
        courseImage: "./images/course-3.jpg",
        courseName: "Bases Matemáticas dios Álgebra Ecuacion",
        courseOwner: "Jassica Miller",
        bgClassName: "bg-color-3",
        textClassName: "text-color-3",
        moreDetails: "More Details",  
    },
      
  ];

export default NewestCourse;