const CourseAdvisor = [
    {
        id:"1",
        advisorImage: "./images/advisor6.jpg",
        advisorName:"James Brook",
        advisorProfession:"Project Management Expert",
        advisorFacebook:"facebook.com",
        advisorTwitter:"twitter.com",
        advisorInsta:"instagram.com",
        advisorLinkedin:"linkedin.com",
    },
    {
        id:"2",
        advisorImage: "./images/advisor7.jpg",
        advisorName:"Jassica Miller",
        advisorProfession:"QA Project Expert",
        advisorFacebook:"facebook.com",
        advisorTwitter:"twitter.com",
        advisorInsta:"instagram.com",
        advisorLinkedin:"linkedin.com",
    },
    {
        id:"3",
        advisorImage: "./images/advisor4.jpg",
        advisorName:"Alister Cock",
        advisorProfession:"Project Management Expert",
        advisorFacebook:"facebook.com",
        advisorTwitter:"twitter.com",
        advisorInsta:"instagram.com",
        advisorLinkedin:"linkedin.com",
    },
    {
        id:"4",
        advisorImage: "./images/advisor5.jpg",
        advisorName:"Lina Ninja",
        advisorProfession:"QA Project Expert",
        advisorFacebook:"facebook.com",
        advisorTwitter:"twitter.com",
        advisorInsta:"instagram.com",
        advisorLinkedin:"linkedin.com",
    },
];
export default CourseAdvisor